### ISSUE TITLE
source.changes publishing

### ISSUE THREAD

**Issue by tsimonq2** [Ferdi265/wl-mirror-debian#1]
It's generally a bad idea to publish signed source.changes files directly. Can be used maliciously, potentially, if the signature is weak.

On a somewhat related note:
```
$ dput ftp-master wl-mirror_0.13.2-1_amd64.changes
D: Setting host argument.
Checking signature on .changes
gpg: /tmp/wl-mirror_0.13.2-1_amd64.changes: Valid signature from E27F2CF8458C2FA4
Checking signature on .dsc
gpg: /tmp/wl-mirror_0.13.2-1.dsc: Valid signature from E27F2CF8458C2FA4
Uploading to ftp-master (via ftp to ftp.upload.debian.org):
  Uploading wl-mirror_0.13.2-1.dsc: done.
  Uploading wl-mirror_0.13.2.orig.tar.gz: done.    
  Uploading wl-mirror_0.13.2.orig.tar.gz.asc: done.
  Uploading wl-mirror_0.13.2-1.debian.tar.xz: done.
  Uploading wl-mirror-dbgsym_0.13.2-1_amd64.deb: done.  
  Uploading wl-mirror_0.13.2-1_amd64.buildinfo: done.
  Uploading wl-mirror_0.13.2-1_amd64.deb: done.  
  Uploading wl-mirror_0.13.2-1_amd64.changes: done.
Successfully uploaded packages.
```

https://tracker.debian.org/news/1452223/wl-mirror-0131-1-migrated-to-testing/

**Comment by Ferdi265** [comment]
Hi! Thanks for uploading again.

Regarding the signed .changes files: would you recommend just not signing them in the GitHub release or dropping some files from the GitHub release entirely?

I'm open to suggestions in how to handle the release of new versions.

**Comment by tsimonq2** [comment]
I would say just use `debsign` to unsign the source.changes file (and related files) before uploading to GitHub. If you already GPG-sign your tarball (which is generally a good idea, see `lxqt-build-tools` and related packaging), there shouldn't be a need to do that extra step.

Thanks!

**Comment by Ferdi265** [comment]
I unsigned the `.changes`, `.buildinfo`, and `.dsc` files in the releases in this repo and will upload newer releases with unsigned `.changes`, `.buildinfo`, and `.dsc` files :+1:

Thanks for the heads-up!
