### ISSUE TITLE
Consider your tagging

### ISSUE THREAD

**Issue by tsimonq2** [Ferdi265/wl-mirror-debian#4]
This is your repo and you are the maintainer. That being said, I thought I'd give you some points for your consideration, based on my own prior experience:
 - Usually, I'd tag an upload with `debian/VERSION_NUMBER` once it's in the archive, with a copy of the packaging that exactly matches what is in Debian. Helps a lot when you want to know who made a change and when (usually with `git blame`).
 - There's no hard policy about upstream tags. That being said, unless this is just a soft fork of your upstream, I'd argue that those tags could be a bit of a red herring. Totally your decision.
 -  I've added this repo to my RSS feed of things I usually check. If you have an urgent upload, or if I don't get to sponsorship within a few days of new commits here, just send me an email as you've done already. I'm happy to help.
 - When you prepare a new upload, please make sure to test it. You're the upstream, I'm trusting that you know your package and what it does. As long as Lintian doesn't complain and your copyright is okay, I have no issue continuing to sponsor whatever you need.

Thanks!

**Comment by Ferdi265** [comment]
Hi!

Thanks for the insights!

Ad Tags: Tagging things as what actually landed in the Debian archives is a great idea, and I will definitely do something like that; the current tagging scheme here is mostly ad-hoc and something I will think about.

Ad announcing new releases and RSS: Thanks, noted.

Ad Testing: I currently only have a VM setup that only allows very basic testing, but I'm generally moving towards more extensive testing of wl-mirror on all distros I'm directly involved with packaging for. I absolutely understand that Maintainership in Debian implies responsibilities about package testing and package quality and will be more thorough for future releases.

I will be leaving this open until I have decided on a tagging scheme.

**Comment by tsimonq2** [comment]
> I absolutely understand that Maintainership in Debian implies responsibilities about package testing and package quality and will be more thorough for future releases.

I never said it was *un*tested, just a reminder. Thanks for what you do :)

**Comment by Ferdi265** [comment]
There are now `debian/0.x.y-r` tags for all versions of wl-mirror that actually made it into the Debian archives. The original tagging scheme is retained as well, tagging the first commit targeting the corresponding upstream version.

Extracting a `.debian.tar.xz` for a specific release at the corresponding `debian/` tag should apply with no diffs.

The new tagging scheme is now also documented in this repo's README.
