### ISSUE TITLE
Please update to Standards-version 4.7.0

### ISSUE THREAD

**Issue by tsimonq2** [Ferdi265/wl-mirror-debian#5]
Here is the upgrade checklist: https://www.debian.org/doc/debian-policy/upgrading-checklist.html#version-4-7-0

I do not see anything in your packaging that needs to be changed. Feel free to do this with your next upload.

**Comment by Ferdi265** [comment]
Thanks! I'll fix that before the next package update.

**Comment by Ferdi265** [comment]
should be fixed as of 053973d, but waiting on the debian mentors run before closing this.

**Comment by Ferdi265** [comment]
Mentors complains that 4.7.0 is too new, but no other nits. I assume this will become the "current" standards version in due time, so closing this.

**Comment by Ferdi265** [comment]
As an additional note, I have pushed 0.16.5-2 with this and the copyright changes.
