### ISSUE TITLE
Clear up Copyright of bundled wayland-protocols and wlr-protocols

### ISSUE THREAD

**Issue by Ferdi265** [Ferdi265/wl-mirror-debian#6]
The current package doesn't attribute the copyright of the bundled `proto/wayland-protocols/` and `proto/wlr-protocols` in `debian/copyright`.

`wayland-protocols` can likely be replaced with the Debian package `wayland-protocols`, but `wlr-protocols` is not packaged in Debian so needs to be described here. I'm also not sure what the policy is on parts of an upstream source tarball that isn't used in the Debian package (i.e. do I need to attribute the copyright of `proto/wayland-protocols` in my package even if I don't use it and instead use the Debian `wayland-protocols` package).

**Comment by Ferdi265** [comment]
@tsimonq2 do you know how this should be handled?

**Comment by Ferdi265** [comment]
Should be fixed as of 7223bdc, but waiting on the debian mentors run before closing this.

**Comment by Ferdi265** [comment]
lintian and mentors looks clean on this, closing. `lrc` still isn't sure about the exact license, but this should do for now.

**Comment by tsimonq2** [comment]
You'll also want to exclude these from your tarballs.

**Comment by Ferdi265** [comment]
> You'll also want to exclude these from your tarballs.

Implemented as of wl-mirror commit [319cfd9](https://github.com/Ferdi265/wl-mirror/commit/319cfd90f3b7851f9bf8f228526e2c2f76a8bb90). This now creates an alternative `-nowlp` tarball that will be uploaded to GitHub releases along with the other signed tarball so that Debian can get one that doesn't contain wayland-protocols.

Will integrate this into the next Debian package release.
